apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server  # Match this label with the label in the Pod template
  template:
    metadata:
      labels:
        app: prometheus-server  # Match this label with the selector label
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/config
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config-map

