alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-microservice'
    scrape_interval: 15s
    static_configs:
      - targets: ['my-microservice:3005']

route:
  group_by: ['alertname', 'job']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#your-slack-channel'
        api_url: 'https://hooks.slack.com/services/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'
