version: '3.8'
services:
  webapp:
    build: ./
    ports: 
      - 3005:3000
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: effect
      DB_DATABASE : test
    networks:
      - frontend
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    ports:
      - 3310:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=effect
      - MYSQL_DATABASE=test
      - MYSQL_HOST=mysql

    volumes:
      - data:/var/lib/mysql
    networks:
      - frontend

networks:
  frontend:

volumes:
  data:
