version: '3.8'
services:
  webapp:
    build: ./
    ports: 
      - 3005:3000
    networks:
      - frontend
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    ports:
      - 3310:3306
    environment:
      - MYSQL_USER=gladys
      - MYSQL_PASSWORD=effect
      - MYSQL_DATABASE=test

    volumes:
      - data:/var/lib/mysql
    networks:
      - frontend

networks:
  frontend:

volumes:
  data:
